version: '3.8'
services:
  web:
    build: ./
    command: sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app/:/usr/src/Kvartirka
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  db:
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin_kv
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=comment_db
volumes: 
    postgres_data: {}